// REAL REVIEWS ONLY - Manually copied from actual Google My Business pages
// NO FAKE REVIEWS - These are exact copies from Google

const REAL_REVIEWS = [
    {
        id: "real-001",
        customerName: "Ingrid Patton",
        rating: 5,
        comment: "Sai was very patient methodical finding the reason for tripping breaker and updating wall outlets. He was easy to work with and gave additional thoughts to replace bad wire to outdoor fixture.",
        date: "06/17/2025",
        formattedDate: "June 17, 2025",
        location: "",
        service: "Electrical troubleshooting, outlet updates",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-002",
        customerName: "Andy Piontek",
        rating: 5,
        comment: "Great service!",
        date: "06/13/2025",
        formattedDate: "June 13, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-003",
        customerName: "Steven Janas",
        rating: 5,
        comment: "Excellent work by Bo as always. He's a pleasure to work with!!!",
        date: "06/04/2025",
        formattedDate: "June 4, 2025",
        location: "",
        service: "Electrical work",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-004",
        customerName: "Lindsay Kempter (violets_will)",
        rating: 5,
        comment: "Needed my electric meter reattached to the house on our back deck and the tech was in and out in 30 mins. Quick and professional, excellent work!",
        date: "06/02/2025",
        formattedDate: "June 2, 2025",
        location: "",
        service: "Electric meter reattachment",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-005",
        customerName: "Martin O'Hara",
        rating: 5,
        comment: "On time. No fuss. All done quickly.",
        date: "05/24/2025",
        formattedDate: "May 24, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-006",
        customerName: "Franklin Wassmer",
        rating: 5,
        comment: "Very knowledgeable. Quick and excellent service.",
        date: "05/22/2025",
        formattedDate: "May 22, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-007",
        customerName: "Sara Hansard",
        rating: 5,
        comment: "Sai was very knowledgeable and got the job done excellently.",
        date: "05/20/2025",
        formattedDate: "May 20, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-008",
        customerName: "Charles Olwell",
        rating: 5,
        comment: "Bowls professional, quick, friendly, and accurate in his assessment.",
        date: "05/19/2025",
        formattedDate: "May 19, 2025",
        location: "",
        service: "Electrical assessment",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-009",
        customerName: "Kenneth Heyer",
        rating: 5,
        comment: "Bo was outstanding and the price was reasonable. For all future work I will call your firm—and request Bo.",
        date: "05/15/2025",
        formattedDate: "May 15, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-010",
        customerName: "Michael Jacob",
        rating: 5,
        comment: "Quick and efficient service. Technician helped me understand system so I can fix in future without having to call in electrician.",
        date: "05/14/2025",
        formattedDate: "May 14, 2025",
        location: "",
        service: "Electrical service and education",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-011",
        customerName: "Joe George",
        rating: 5,
        comment: "Efficient, thorough, and kind",
        date: "05/12/2025",
        formattedDate: "May 12, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-012",
        customerName: "Gloria Freund",
        rating: 5,
        comment: "Excellent highly professional service at fair price",
        date: "05/07/2025",
        formattedDate: "May 7, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-013",
        customerName: "James Polzin",
        rating: 5,
        comment: "Sai and Bo provided excellent service. They are very knowledgeable and efficient.",
        date: "04/24/2025",
        formattedDate: "April 24, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-014",
        customerName: "Joe George",
        rating: 5,
        comment: "The worker (I missed his name) was thorough and explained everything to me as he found the root of my problem.",
        date: "04/18/2025",
        formattedDate: "April 18, 2025",
        location: "",
        service: "Electrical troubleshooting",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-015",
        customerName: "Franklin Wassmer",
        rating: 5,
        comment: "The service was exceptional. The technician made sure that all the updated outlets were properly wired and was detail oriented in all aspect of the work.",
        date: "04/17/2025",
        formattedDate: "April 17, 2025",
        location: "",
        service: "Outlet updates",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-016",
        customerName: "Phil Schmidt",
        rating: 5,
        comment: "Matt, who runs the business, is very friendly and helpful. Sai, the actual electrician who came to our house, is very knowledgeable and ensured that everything was done as anticipated.",
        date: "04/10/2025",
        formattedDate: "April 10, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-017",
        customerName: "David Young",
        rating: 5,
        comment: "Our electrician Sai was wonderful. Excellent service and great suggestions for us as homeowners about lighting and fixtures. We will definitely use AJ Long again.",
        date: "04/09/2025",
        formattedDate: "April 9, 2025",
        location: "",
        service: "Lighting and fixtures",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-018",
        customerName: "David",
        rating: 5,
        comment: "Our electrician Sai was wonderful. Excellent service and great advice on our lighting and fixtures. We will definitely use AJ Long again.",
        date: "04/09/2025",
        formattedDate: "April 9, 2025",
        location: "",
        service: "Lighting and fixtures",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-019",
        customerName: "MJK -",
        rating: 5,
        comment: "Bo did a great job - thank you very much!!!",
        date: "04/08/2025",
        formattedDate: "April 8, 2025",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-020",
        customerName: "Robert Anthony",
        rating: 5,
        comment: "I appreciate the experience that AJ Long's electricians bring to the job. Their diagnosis and advice on the fix reflect that experience. Their work is well worth the call.",
        date: "04/07/2025",
        formattedDate: "April 7, 2025",
        location: "",
        service: "Electrical diagnosis and repair",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-021",
        customerName: "Patricia Moynihan",
        rating: 5,
        comment: "I've been using AJ Long Electric for about 8 plus years and they are wonderful. Bo is a top notch electrician and has done all sorts of work around my house over the years. he has installed attic fan, security lights and cameras, car chargers, can lights, wiring for a sauna, etc. I've never had one issue with them.",
        date: "Recent",
        formattedDate: "Recent",
        location: "",
        service: "Multiple electrical services",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-022",
        customerName: "Kim Hendricks",
        rating: 5,
        comment: "I have used AJ Long for over 10 years...they have always been exceptional. Today Marcos came on short notice and was marvelous-- hardworking, polite, respectful and diligent. We will stay for another 10 years!",
        date: "Recent",
        formattedDate: "Recent",
        location: "",
        service: "Emergency electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-023",
        customerName: "Stuart Billings",
        rating: 5,
        comment: "AJ Long recently installed an EV charger at my residence and they were fantastic! They kept me informed of when they would do the work and how long it would take. Their prices are competitive and I would definitely recommend them!",
        date: "Recent",
        formattedDate: "Recent",
        location: "",
        service: "EV charger installation",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-024",
        customerName: "Ken Graham",
        rating: 5,
        comment: "I highly recommend AJ Long Electric. All of our kitchen outlets stopped working, but didn't trip the breaker. I called for help and was completely impressed with the service from call to completion. Everything was done by the quickly and professionally. So impressed! Thank you",
        date: "Recent",
        formattedDate: "Recent",
        location: "",
        service: "Kitchen electrical troubleshooting",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-025",
        customerName: "Sandra Bishop",
        rating: 5,
        comment: "We had an appointment to come on a Sunday night. I went to AJ Long's website and was easily able to schedule an appointment *for the next day!* The website was very transparent about the cost for the service call and possible charges.",
        date: "Recent",
        formattedDate: "Recent",
        location: "",
        service: "Emergency electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-026",
        customerName: "Marc",
        rating: 5,
        comment: "Excellent experience! I had trouble with a new light fixture because it kept tripping the breaker every time I tried to turn the light on at the wall switch. After several days of phoning friends and attempting to self trouble shoot with the help of AI, I got nowhere. I called AJ Long Electric and they sent out Sai who showed up within 2-hours of my call (I did not request emergency service). He diagnosed the problem on no time and came up with a quick fix which I nor ChatGPT would have figured out. He was very friendly and also helped to educate me on what was happening which I appreciated after my many failed attempts at fixing this issue myself. I would definitely recommend A.J. Long Electric and I'd recommend asking for Sai.",
        date: "2 weeks ago",
        formattedDate: "2 weeks ago",
        location: "",
        service: "Light fixture troubleshooting",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-027",
        customerName: "Scott Wainwright",
        rating: 5,
        comment: "Suggested options and made recommendations, carried out the work expertly and professionally, cleaned up afterward. Overall, an excellent job!",
        date: "3 weeks ago",
        formattedDate: "3 weeks ago",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-028",
        customerName: "Steph Grayson",
        rating: 5,
        comment: "Arrived on time. He was extremely friendly, and took time to understand what the task was. Quickly identified any unexpected obstacle with a possible solution. He was clean and professional while working. And cleaned up when work was done. I was so happy with the whole process. The work was so well done. Thank you to your team for a truly great experience.",
        date: "3 weeks ago",
        formattedDate: "3 weeks ago",
        location: "",
        service: "Electrical panel replacement or upgrading",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-029",
        customerName: "Lisa Hayes",
        rating: 5,
        comment: "Yesterday, we called AJ and spoke to Matt. Today, Sai came to the house and evaluated the problem. Everything was clearly explained. Excellent service, great team!",
        date: "3 weeks ago",
        formattedDate: "3 weeks ago",
        location: "",
        service: "Electrical troubleshooting",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-030",
        customerName: "Bill Fitzgerald",
        rating: 5,
        comment: "Always excellent customer service and solid professional delivery. Bo is our Go-To Professional who always does exceptional work and leaves the area completely clean.",
        date: "4 weeks ago",
        formattedDate: "4 weeks ago",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-031",
        customerName: "Luke Bunker",
        rating: 5,
        comment: "Of all the vendors I've worked with as a relatively new homeowner, this team provides standout, exemplary service. I have full faith in AJ long to send me the best of the best and I can't say enough nice enough things about their technicians. The upfront estimates are fair, transparent and account for unknowns on the job. Keep up the good work and thanks to you and the team for a job well done!",
        date: "4 weeks ago",
        formattedDate: "4 weeks ago",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-032",
        customerName: "John Groat",
        rating: 5,
        comment: "Sai did a great job confronted with both old electric wiring and water damage. I appreciated his explaining to me what he was doing as he worked. I look forward to an estimate for additional required work.",
        date: "9 weeks ago",
        formattedDate: "9 weeks ago",
        location: "",
        service: "Electrical repair",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-033",
        customerName: "Joan Harrington",
        rating: 5,
        comment: "Bo was friendly, efficient, hard working, considerate and did our attic vent fan and new outlet in a short amount of time and exactly as we asked for.",
        date: "12 weeks ago",
        formattedDate: "12 weeks ago",
        location: "",
        service: "Attic vent fan and outlet installation",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-034",
        customerName: "Mark Smith",
        rating: 5,
        comment: "Fantastic experience. Scheduled the same day I called. John arrived on time, diagnosed my problem immediately, fixed it efficiently, and made a couple of suggestions to prevent recurrence. The charge was reasonable. I would recommend in a heartbeat.",
        date: "13 weeks ago",
        formattedDate: "13 weeks ago",
        location: "",
        service: "Electrical troubleshooting",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-035",
        customerName: "Mark Wells",
        rating: 5,
        comment: "We had Sai come out again yesterday after we had him out last week. He's a real pro. Yesterday he fixed two receptacles outside, placing grey boxes on each receptable so the GFCI would not trip when it rained or snowed. Most important though was he discovered the front light on the lower level was improperly installed, which could have caused a fire and burned down our home. He worked two hours on replacing the wiring and re-installing the light and now the light works properly and it looks great. The price AJ Long Electric charged was very fair. We highly recommend AJ Long Electric.",
        date: "15 weeks ago",
        formattedDate: "15 weeks ago",
        location: "",
        service: "Outdoor electrical repair and safety fixes",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-036",
        customerName: "Joanne Neuber",
        rating: 5,
        comment: "We've relied on family-run AJ Long Electric for over 25 years and appreciate all the work they have done in our home! John, Beau and team are a very qualified, professional group of top-notch electricians.",
        date: "16 weeks ago",
        formattedDate: "16 weeks ago",
        location: "",
        service: "Long-term electrical services",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-037",
        customerName: "Joe Molnar",
        rating: 5,
        comment: "Great experience. I called but didn't leave a message. I instead scheduled for a week out on their web app. Someone then called me and indicate I could get an appointment next day, which is what I wanted in the first place. Got the email estimate and it was about what I expected. I asked how soon the work could be done, and the electrician checked with his manager. The reshuffled his load and he was able to start immediately. Work took about four hours between the cold garage and the basement. He took a brief break for lunch., but then back at it. Very hard working. Skilled electrician who efficiently executed the installation. Couldn't have asked for a better experience.",
        date: "18 weeks ago",
        formattedDate: "18 weeks ago",
        location: "",
        service: "Electrical installation",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-038",
        customerName: "John Saunders",
        rating: 5,
        comment: "Sy showed up exactly on time, surveyed the situation and made a suggestion regarding attaching power to a separate building that worked out perfectly. I've been very happy with the very professional, fast, and knowledgeable work from AJ Long.",
        date: "39 weeks ago",
        formattedDate: "39 weeks ago",
        location: "",
        service: "Building electrical connection",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-039",
        customerName: "Jeremy Plotnick",
        rating: 5,
        comment: "I am very pleased with the service provided by Jason from AJ Long Electric. I had a power outage in the master bedroom and bath and could not figure where the problem was. Jason arrived on the near side of the arrival window and go right to work in diagnosing the problem. He then explained everything to me in terms I could understand and let me see what he was doing while he resolved the issue. All this was done in a timely manner on relatively short notice. I would use this service again and would recommend it to friends/family.",
        date: "43 weeks ago",
        formattedDate: "43 weeks ago",
        location: "",
        service: "Power outage diagnosis and repair",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    },
    {
        id: "real-040",
        customerName: "Tracy Schulberg",
        rating: 5,
        comment: "These guys are outstanding! Great service, great prices and fast workers, wished I had called them 3 weeks ago but will definitely use them again!!!",
        date: "49 weeks ago",
        formattedDate: "49 weeks ago",
        location: "",
        service: "Electrical service",
        verified: true,
        businessLocation: "AJ Long Electric - Main Location",
        source: "google"
    }
];

// Real review statistics from actual Google pages
const REAL_REVIEW_STATS = {
    totalReviews: 40,
    averageRating: 5.0,
    locationStats: {
        'AJ Long Electric - Main Location': {
            reviews: 40,
            rating: 5.0
        },
        'AJ Long Electric - Annandale': {
            reviews: 0,
            rating: 0
        },
        'AJ Long Electric - Burke': {
            reviews: 0,
            rating: 0
        },
        'AJ Long Electric - Bowie': {
            reviews: 0,
            rating: 0
        }
    }
};

// Export for use in testimonials page
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { REAL_REVIEWS, REAL_REVIEW_STATS };
}