# Netlify Configuration - Explicitly override UI settings
# This configuration forces deployment from the root directory

[build]
  # Explicitly set base directory to root (empty string means root)
  base = ""
  # Publish directory is the root of the repository
  publish = "."
  # Functions directory
  functions = "netlify/functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  # Disable secrets scanning for non-sensitive values
  SECRETS_SCAN_ENABLED = "false"

# Redirects configuration
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200

# Catch-all redirect for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
